#!/bin/bash
uwsgi --plugins http,python --protocol=http --wsgi-file wsgi_interface.py --socket :8000 --harakiri 60 --harakiri-verbose --daemonize watchmaker.log --pidfile /tmp/uwsgi.pid --workers 4
 
